clusters:
- name: default-cluster
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lSQUlVZFRhYk5WZVlidjlyS1IyWG9ZZ0F3RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdIaGNOTWpNd05ESXdNVE13TnpJNVdoY05Nek13TkRJd01UTXdOekk1V2pBTgpNUXN3Q1FZRFZRUURFd0pqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS3QzCklXWXZYUW9EeXdUN1FSOU1BQjFyZnEzTUZ4Q3NKa09GbkxTazFwRXRIWmlwZ3hBTDU4S0ZJOEgraFh5Rkg5aVUKVzY3OUplNG1venRjMXgwalY5OE1ldWVpa0MzaThtTHNFTDZXelR4eklXRS8xbHJIcGdUdFE5UDd5TkprcTRBZApkQWIzcVZiUzI4UGFiRjJUc2pnZkttV1dJNXFlR1pRY0UzSWYyVEtMK3hjWmpjY1ZVY1ozMm5RSDZzUmw2bGZnCnBLYVFMa2RoMHBOcU81MHZiMXd2NkRMM1BJOHl6VlMrRElRejYvWEJ6bVdPRndiVUZEakhVQ2RhVW9GK01QenkKWDRwQ3dnd2F6dWo4TFdnTUIreFFkcS9wTGhtcXJ2QU1rSFU0MTZVRXNzK0I0cmNYWVVmNm9vSUNnWnpWTSt6MApsVkJieldFOGt1dmVCSlZlNWhzQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0dtTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZNaHFHSEtYQ0tEaE5KaGNNSnpQSzFBMmluQWhNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDcCtyNFdPUlYwMTZnSFB1YURrVnJ5WFBoTHcxQUh6ZStRakJGZlNIRlhkSHhqSWFybwpFT09RT1J5YmIrVTNLOTIyRHBPbzU1bnhxQ3VxU0NEeXlqbjBmNnpuK2ZmT01BVFg5T0tsQ1REMXU5aDhsRytYCmFIQk50UlBoV2JDeEUvRUJNbW5IaUEyUCs0U2ZtZmRHT0djWS9EaEZoQ04wTjB5STBiSFdxZTJhMWRFR3BRU2UKd0R1SWdLNnZiWEdjSmZHaFZ2Y013bytVZTdtZGFFeG8zbUs0aVp1L3lUQW4vaDB1YnRDcDhEK3g2YXFZWVA3bQpkSXc4QXNnbjFSWkZoNzFpekpEa3NEQkU3Q0xpYTliUldFSEFIc3lGaTBXcmJBK1FZNWhETENQTFZJTHBWUEExCktVZnJ4L09BUXBMVE5pWVZGbEJvSzJWYWpYTzBDaDc3MVJwMQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.c-7dd02e8.kyma.ondemand.com
users:
- name: default-user
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImNaN0RGTWFHOG5JRkFYRVFZZ0JTM1dfUXhJYjdINmZ4RWxBT1ZLNW4wOTAifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ0dXRvcmlhbCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJ0dXRvcmlhbC1zZXJ2aWNlLWFjY291bnQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoidHV0b3JpYWwtc2VydmljZS1hY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNmU0ZjMwMDMtY2MyZi00ZTIyLTlkMDMtYTBmNWE2ODk5NDM5Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnR1dG9yaWFsOnR1dG9yaWFsLXNlcnZpY2UtYWNjb3VudCJ9.tLnWJlha9P4xdV5rEz0f0jnE545ZtL6eaviBhgGcRJZoMHhx1DkcqNxETkzP8jEVilqSJI9eCyNnddTcHgDNgpRtMyfVmnOeGMBd8fznTJs4oBPGq7H9SqWKYlNU_uiLfWSXCvrLzGO4PwuoVO2xAM7VvWSWlcr7uZEhN1xXeVrA3eiyq3B42ACqDGXpTtXXPNn6mq_GZyjBB2qiC9xDgS1zH3t5W8pE43UJDeLdr2j0lndh8U6tqgScnv_FVet2a0yvrRi5Jl7tevl8gJa8RUoCVUXMHBI_lcnq2P6GxhAjav00xIxtkjklQzmkKAg6Bi1OCfCApHcZv0NdRSdkpifDV8iuzz78EOV9-9xaQI-8uPadaZgz-gVLXFmZ2dqQ2WOwTYWArSARqe2vmhXE8yR6oU5IdCYbku17ZQOwuV0F9-2VQjA-1n6cMTZJ2k4pVzErV6f2EVvSxYxDPIv4HjgBJb15hG3AI7itu4Q6_5GTS26Zz54_kVY0kvWHsSp-L0IsUQ_b9YXgmJ2gAJ6ceBqh_xlkFAWfB2yl2VoPNppdz-z2CmgfXW4HxJKogc1nMAAQef1L2NPRNL5FCZHkVM07XjKj8WJwThLBNjhPGon7l9U1i3jShlmWZOLipozBFw4ulPDh3-s8RLFedaKuU6otON5MiXmWqFQ85FTFpYE
contexts:
- name: default-context
  context:
    cluster: default-cluster
    namespace: tutorial
    user: default-user
current-context: default-context
---
general:
  buildTool: "docker"
  containerImageName: "mariuszwie/test"
  containerImageTag: "0.1"
  containerRegistryUrl: "https://index.docker.io/v1/"
service:
  automaticVersioning: false
  dockerConfigJsonSecretTextCredentialsId: "decker-secret"
  Release:
    kubeConfigSecretTextCredentialsId: "kubernetes-secret"
steps:
  kanikoExecute:
    dockerfilePath: "Dockerfile"
stages:
  Build:
    kanikoExecute: true
  Acceptance:
    kubernetesDeploy: false
  Release:
    kubernetesDeploy: true
    deployTool: "kubectl"
    namespace: "tutorial"
    createDockerRegistrySecret: true
    appTemplate: "k8s_apptemplate.yaml"
    deployCommand: "apply"